config/routes.rb
Rails.application.routes.draw do
  resources :lists
end

app/models/list.rb
class List < ActiveRecord::Base
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController <ApplicationController
  def index
    @lists = List.all
    render :index
  end

  def show
    @list = List.find(params[:id])
    render :show
  end

  def new
    @list = List.new
    render :new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
    render :edit
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to lists_path
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private
  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<% render 'layouts/errors', :object => @list %>

<%= form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit List</h1>

<!-- # <% if @list.errors.any? %>
#   <h3>Please fix these errors:</h3>
#   <ul>
#     <% @list.errors.full_messages.each do |message| %>
#       <li><%= message %></li>
#     <% end %>
#   </ul>
# <% end %>
#
# <%= form_for @list do |f| %>
#   <%= f.label :name %>
#   <%= f.text_field :name %>
#   <%= f.submit %>
# <% end %> -->

<%= render 'form' %>

app/views/lists/index.html.erb
<h1>Lists</h1>
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<h1>New List</h1>

<!-- # <% if @list.errors.any? %>
#   <h3>Oops, there were some errors.  Please try again:</h3>
#   <ul>
#     <% @list.errors.full_messages.each do |message| %>
#       <li><%= message %></li>
#     <% end %>
#   </ul>
# <% end %>
#
# <%= form_for @list do |f| %>
#   <%= f.label :name %>
#   <%= f.text_field :name %>
#   <%= f.submit %>
# <% end %> -->

<%= render 'form' %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<p><%= link_to 'Edit', edit_list_path(@list) %></p>
<p><%= link_to 'Delete', list_path(@list),
        :data => {:confirm => 'Are you sure?',
              :method => 'delete'} %></p>

<p><%= link_to "Return to Lists", lists_path %></p>